generators:
  - cluster-specific-policies/ztpclustera.yaml
 # - cluster-specific-policies/cnfdb2.yaml
 # - cluster-specific-policies/eric1.yaml
 #- cluster-specific-policies/virt01-day2.yaml
 #- common-policies/common-4.8.yaml
 #- common-policies/common-4.9.yaml
    #- group-policies/group-du-sno.yaml
    # - group-policies/platform-upgrade-sno.yaml
    #- site-specific-policies/westford-lab.yaml
  #- site-specific-policies/telco-5g-lab.yaml
resources:
# List of Namespace*.yaml required by the PolicyGenTemplate*.yaml
  - ns.yaml
